spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lufthansa?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  sql:
    init:
      mode: always

okta:
  oauth2:
    issuer: https://dev-25860839.okta.com/oauth2/default
    client-id: 0oaf2ux87cPBoMgGW5d7
    client-secret: eVtnCy4ucG6GCdbW6BsH8rzExNV0bCFCDEE_szpcSRwef0avtvLgjzilWgmILdEe
