spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lufthansa?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  spring:
    jpa:
      show-sql: true


# Logging Configuration
#logging:
#  level:
#    root: info
#    com:
#      lufthansa:
#        flightbooking:
#          controller: debug
#          service: info
